
url: http://shanisebarona.com/
permalink: /:categories/:title/

author:
  name: Shanise Barona
  email: hi@shanisebarona.com

title: Shanise Barona
description: "Software Engineer."
twitter: "@shanisebarona"
