
title: SB | software engineer 
description: "Shanise Barona's corner of the internet."
url: http://shanisebarona.com/
repository: shanisebarona/shanisebarona.github.io

author:
  name: Shanise Barona
  email: hi@shanisebarona.com
  linkedin: https://www.linkedin.com/in/shanisebarona/




